In [19]:
print("Jay Ganesh")

Jay Ganesh

In [20]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler,OneHotEncoder
import pickle

In [21]:
data=pd.read_csv(r"D:\ProjectAarya\GEN AI\Code\Ch13\Churn_Modelling.csv")

In [22]:
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [23]:
data.drop(['RowNumber','CustomerId','Surname',],axis='columns',inplace=True)

In [24]:
label_gender=LabelEncoder()
data['Gender']=label_gender.fit_transform(data['Gender'])

In [25]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

ohegeo = OneHotEncoder(handle_unknown='ignore', sparse_output=False)  # sparse_output=False avoids sparse issues
geo_encoded = ohegeo.fit_transform(data[['Geography']])  # Full column as DataFrame, no [ ]
geo_encodeddf = pd.DataFrame(geo_encoded, columns=ohegeo.get_feature_names_out())

In [26]:
geo_encodeddf

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [27]:
data=pd.concat([data.drop('Geography',axis='columns'),geo_encodeddf],axis='columns')

In [28]:
data.head()

   CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0          619       0  ...                0.0              0.0
1          608       0  ...                0.0              1.0
2          502       0  ...                0.0              0.0
3          699       0  ...                0.0              0.0
4          850       0  ...                0.0              1.0

[5 rows x 13 columns]

In [29]:
X=data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']
X

      CreditScore  Gender  ...  Geography_Germany  Geography_Spain
0             619       0  ...                0.0              0.0
1             608       0  ...                0.0              1.0
2             502       0  ...                0.0              0.0
3             699       0  ...                0.0              0.0
4             850       0  ...                0.0              1.0
...           ...     ...  ...                ...              ...
9995          771       1  ...                0.0              0.0
9996          516       1  ...                0.0              0.0
9997          709       0  ...                0.0              0.0
9998          772       1  ...                1.0              0.0
9999          792       0  ...                0.0              0.0

[10000 rows x 12 columns]

In [30]:
y

0       101348.88
1       112542.58
2       113931.57
3        93826.63
4        79084.10
          ...
9995     96270.64
9996    101699.77
9997     42085.58
9998     92888.52
9999     38190.78
Name: EstimatedSalary, Length: 10000, dtype: float64

In [31]:

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.14,random_state=6)
##Scalling the features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.fit_transform(X_test)

In [32]:
with open('gender.pkl','wb') as f:
    pickle.dump(label_gender,f)
with open('geography.pkl','wb') as f:
    pickle.dump(ohegeo,f)
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

### ANN Regression Problem Statement

In [34]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [35]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1)# Applying no activation function here because we are working with regression task 
])

c:\Users\Jay\anaconda3\envs\ch13\lib\site-packages\keras\src\layers\core\dense.py:95: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [36]:
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

In [38]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

log_dir="regressionlogs/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [39]:
earlystoppingcallback=EarlyStopping(monitor='val_loss',patience=4,restore_best_weights=True)

In [42]:
history=model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[earlystoppingcallback,tensorboard_callback]
)

Epoch 1/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50277.1562 - mae: 50277.1562 - val_loss: 50091.9922 - val_mae: 50091.9922
Epoch 2/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50211.9727 - mae: 50211.9727 - val_loss: 50048.5586 - val_mae: 50048.5586
Epoch 3/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50153.6328 - mae: 50153.6328 - val_loss: 50011.4766 - val_mae: 50011.4766
Epoch 4/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50104.2539 - mae: 50104.2539 - val_loss: 49980.1016 - val_mae: 49980.1016
Epoch 5/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 50059.4609 - mae: 50059.4609 - val_loss: 49960.8906 - val_mae: 49960.8906
Epoch 6/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 50016.7227 - mae: 50016.7227 - val_loss: 49927.7266 - val_mae: 49927.7266
Epoch 7/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - loss: 49985.1484 - mae: 49985.1484 - val_loss: 49918.1914 - val_mae: 49918.1914
Epoch 8/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49951.8086 - mae: 49951.8086 - val_loss: 49900.9570 - val_mae: 49900.9570
Epoch 9/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49925.1406 - mae: 49925.1406 - val_loss: 49895.2695 - val_mae: 49895.2695
Epoch 10/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49904.6562 - mae: 49904.6562 - val_loss: 49879.8789 - val_mae: 49879.8789
Epoch 11/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49882.1328 - mae: 49882.1328 - val_loss: 49870.7539 - val_mae: 49870.7539
Epoch 12/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49859.6562 - mae: 49859.6562 - val_loss: 49851.1523 - val_mae: 49851.1523
Epoch 13/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49842.2734 - mae: 49842.2734 - val_loss: 49849.4062 - val_mae: 49849.4062
Epoch 14/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49824.1953 - mae: 49824.1953 - val_loss: 49849.1641 - val_mae: 49849.1641
Epoch 15/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49810.0352 - mae: 49810.0352 - val_loss: 49837.5391 - val_mae: 49837.5391
Epoch 16/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49793.8711 - mae: 49793.8711 - val_loss: 49831.0742 - val_mae: 49831.0742
Epoch 17/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49779.4922 - mae: 49779.4922 - val_loss: 49825.1367 - val_mae: 49825.1367
Epoch 18/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49763.6992 - mae: 49763.6992 - val_loss: 49836.2656 - val_mae: 49836.2656
Epoch 19/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49749.7500 - mae: 49749.7500 - val_loss: 49832.6836 - val_mae: 49832.6836
Epoch 20/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49738.6797 - mae: 49738.6797 - val_loss: 49837.5117 - val_mae: 49837.5117
Epoch 21/100
269/269 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49726.4883 - mae: 49726.4883 - val_loss: 49830.2461 - val_mae: 49830.2461

In [43]:
###Evaluate the model

%load_ext tensorboard

In [46]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6006 (pid 5296), started 0:00:46 ago. (Use '!kill 5296' to kill it.)

In [48]:
test_loss,test_mae=model.evaluate(X_test,y_test)

44/44 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49825.1367 - mae: 49825.1367

In [50]:
print(test_loss)

49825.13671875

In [51]:
model.save('regressionmodel.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.